version: '3.8'

services:
  app:
    image: customer-ms
    build: .
    ports:
      - "3001:3000"
    env_file:
      - .env 
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data: